stages:
  - test
  - stats
  - release

stylecheck:
  stage: test
  tags:
    - python3
    - php
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
    - composer-checkstyle

unittest:
  stage: test
  tags:
    - python3
    - progstats
    - php
    - xdebug
    - mysqli
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
    - composer-unittest

release_upload:
  stage: release
  only:
    - master
  tags:
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
    - github-release-upload $(cat version) "$(changelog-reader)"
    - gitlab-release-upload $(cat version) "$(changelog-reader)"

gitstats:
  stage: stats
  tags:
    - python3
    - gitstats
    - progstats
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
    - gitstats-gen

docgen:
  stage: stats
  tags:
    - python3
    - progstats
    - php
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
    - composer-docgen
