stages:
  - mirror
  - test
  - release
  - deploy

github_mirror:
  stage: mirror
  tags:
    - github_namboy94_push
  script:
    - git checkout master
    - git pull
    - git push git@github.com:namboy94/welwitschi-auth.git master -f
    - git checkout develop
    - git pull
    - git push git@github.com:namboy94/welwitschi-auth.git develop -f

lint:
  stage: test
  tags:
    - php-7.1
    - composer
  script:
    - composer update
    - ./lint.sh

unittest:
  stage: test
  tags:
    - composer
    - php-7.1
    - progstats
    - welwitschi-auth-test-db
  script:
    - echo $TEST_DB_PASS > DB_PASS.secret
    - composer update
    - ./unittest.sh
    - rsync -av coverage/ /var/www/progstats.namibsun.net/public/coverage/welwitschi-auth --delete-before
    - rm DB_PASS.secret

upload_release_to_github:
  stage: release
  only:
    - master
  tags:
    - python
  script:
    - mkdir -p artifacts
    - git clone https://gitlab.namibsun.net/namboy94/ci-scripts.git
    - python ci-scripts/src/changelog-reader/changelog-reader.py -c CHANGELOG -d current_changelog
    - python ci-scripts/src/github-release-uploader/github-release-uploader.py namboy94 welwitschi-auth $GITHUB_ACCESS_TOKEN
      $(cat version) current_changelog artifacts -b master

upload_release_to_gitlab:
  stage: release
  only:
    - master
  tags:
    - python
  script:
    - mkdir -p artifacts
    - git clone https://gitlab.namibsun.net/namboy94/ci-scripts.git
    - python ci-scripts/src/changelog-reader/changelog-reader.py -c CHANGELOG -d  current_changelog
    - python ci-scripts/src/gitlab-release-uploader/gitlab-release-uploader.py namboy94 welwitschi-auth $GITLAB_ACCESS_TOKEN
      $(cat version) current_changelog artifacts -b master -u https://gitlab.namibsun.net
