stages:
  - mirror
  - test

variables:
  GITHUB_OAUTH_TOKEN: "$GITHUB_ACCESS_TOKEN"
  GITLAB_ACCESS_TOKEN: "$GITLAB_ACCESS_TOKEN"
  TEST_DB_PASS: "$TEST_DB_PASS"

github_mirror:
  stage: mirror
  tags:
    - linux-buildserver
  script:
    - git checkout master
    - git pull
    - git push git@github.com:namboy94/welwitschi-auth.git master -f
    #- git checkout develop
    #- git pull
    #- git push git@github.com:namboy94/welwitschi-auth.git develop -f

lint:
  stage: test
  tags:
    - linux-buildserver
  script:
    - ./lint.sh

unittest:
  stage: test
  tags:
    - linux-buildserver
  script:
    - ./unittest.sh