stages:
  - mirror
  - test
  - publish

github_mirror:
  stage: mirror
  tags:
    - linux-buildserver
  script:
    - git checkout master
    - git pull
    - git push git@github.com:namboy94/welwitschi-auth.git master -f
    #- git checkout develop
    #- git pull
    #- git push git@github.com:namboy94/welwitschi-auth.git develop -f

lint:
  stage: test
  tags:
    - linux-buildserver
  script:
    - cd .checkstyle
    - php run.php --src ../src

trigger_packagist_update:
  stage: publish
  tags:
    - linux-buildserver
  script:
    - curl -XPOST -H'content-type:application/json' 'https://packagist.org/api/update-package?username=$PACKAGIST_API_TOKEN&apiToken=API_TOKEN' -d'{"repository":{"url":"https://packagist.org/packages/namboy94/welwitschi-auth"}}'