stages:
  - mirror
  - test

variables:
  GITHUB_OAUTH_TOKEN: "$GITHUB_ACCESS_TOKEN"
  GITLAB_ACCESS_TOKEN: "$GITLAB_ACCESS_TOKEN"

github_mirror:
  stage: mirror
  tags:
    - linux-buildserver
  script:
    - git checkout master
    - git pull
    - git push git@github.com:namboy94/welwitschi-auth.git master -f
    #- git checkout develop
    #- git pull
    #- git push git@github.com:namboy94/welwitschi-auth.git develop -f

lint:
  stage: test
  tags:
    - linux-buildserver
  script:
    - cd .checkstyle
    - php run.php --src ../src

unittest:
  stage: test
  tags:
    - linux-buildserver
  script:
    - composer update
    - vendor/bin/phpunit src/test